import React, {Component} from 'react';
import Header from '../components/header';
import Footer from '../components/footer';
import { connect } from 'react-redux';


class About extends Component{


    render(){
        return (
            <div className="container">
                <Header></Header>
                <div className="w-1000 s-center our-container">
                    <h2 className="mb-30">服务条款</h2>

                    <h3>一、总则</h3>
                    <p>
                        <span>1.1</span><span>、</span><span>&nbsp;</span><span>用户在使用神州会展服务前，应当仔细阅读《神州会展服务协议》（以下简称</span><span>“</span><span>本协议</span><span>”</span><span>）的全部内容。</span><span></span>
                    </p>
                    <p>
                        <span>1.2</span><span>、</span><span>&nbsp;</span><span>用户应当同意本协议的全部条款并按照页面上的提示完成全部的注册程序。用户在进行注册程序过程中点击</span><span>"</span><span>注册</span><span>"</span><span>按钮即表示用户与神州会展达成以下协议，完全接受本协议项下的全部条款，本协议即在用户与神州会展之间产生法律效力，对双方均具有法律约束力。</span><span></span>
                    </p>
                    <p>
                        <span>1.3</span><span>、</span><span>&nbsp;</span><span>用户注册成功后，神州会展将给予每个用户一个用户帐号（用户手机号）及相应的密码，该用户帐号和密码由用户负责保管；用户应当对以其用户帐号进行的所有活动和事件负法律责任。</span><span></span>
                    </p>
                    <p>
                        <span>1.4</span><span>、</span><span>&nbsp;</span><span>神州会展服务协议及公告可由神州会展随时更新，且无需另行通知。神州会展有权对上述条款进行修改，修改后的协议一旦公布即有效替代原有协议。用户可随时查询最新协议。用户在使用神州会展提供的各项服务之前，应仔细阅读本协议及本协议。用户在使用相关服务时</span><span>,</span><span>应关注并遵守其所适用的相关条款。用户如不同意本服务协议及</span><span>/</span><span>或随时对其的修改，可以主动取消神州会展提供的服务；用户一旦使用神州会展服务，即视为用户已了解并完全同意本协议中的各项内容，包括神州会展对本协议随时所做的任何修改，并成为神州会展用户。</span><span></span>
                    </p>
                    <p>
                        <span>&nbsp;</span>
                    </p>
                    <h3>二、相关定义</h3>
                    <p>
                        <span>2.1</span><span>、</span><span>&nbsp;</span><span>神州会展：指成都快乐马儿网络科技有限公司运营和所有的会展服务信息网络平台。成都快乐马儿科技有限公司通过神州会展平台向用户和商户提供相关互联网端及移动端信息服务。</span><span></span>
                    </p>
                    <p>
                        <span>2.2</span><span>&nbsp;</span><span>、招标信息：指用户通过神州会展平台发布的会展需求信息，该信息可能会被推送至商户手中，实质上是一种信息的传送，并非传统意义上的招标。</span><span></span>
                    </p>
                    <p>
                        <span>2.3</span><span>、</span><span>&nbsp;</span><span>会展服务信息：</span><span>&nbsp;</span><span>指商户通过神州会展平台发布的商品或服务售卖信息，包含商品或服务的价格或租金、介绍、使用说明等。</span><span></span>
                    </p>
                    <p>
                        <span>2.4</span><span>、</span><span>&nbsp;</span><span>用户：</span><span>&nbsp;</span><span>指完成神州会展平台注册程序，获得可以登陆神州会展会员系统权限的正式注册会员。</span><span></span>
                    </p>
                    <p>
                        <span>2.5</span><span>、</span><span>&nbsp;</span><span>商户：</span><span>&nbsp;</span><span>指通过神州会展平台发布会展服务信息，向用户提供商品或服务的自然人、法人或其他组织。</span><span></span>
                    </p>
                    <p>
                        <span>2.6</span><span>、</span><span>&nbsp;</span><span>一站式服务商家：指有能力单独帮助用户解决参展过程中遇到的全部问题或提供所有服务的商户。</span><span></span>
                    </p>
                    <p>
                        <span>2.7</span><span>、</span><span>&nbsp;</span><span>专业分项目服务商户：指有能力帮助用户解决参展过程中遇到的部分问题或提供专项服务的商户。</span><span></span>
                    </p>
                    <p>
                        <span>&nbsp;</span>
                    </p>
                    <h3>三、用户资格及注册</h3>
                    <p>
                        <span>3.1</span><span>、</span><span>&nbsp;</span><span>用户应为具有完全民事权利能力和民事行为能力的自然人、法人，或是能够独立承担民事责任能力的其他组织。用户若不具有前述规定的法律能力资格，须经法定代理人同意或由法定代理人代理，或是得到有权主体授权后进行注册、交易。</span><span></span>
                    </p>
                    <p>
                        <span>3.2</span><span>、</span><span>&nbsp;</span><span>用户使用神州会展提供的网络平台服务前，应自行准备如下设备并承担如下开支：</span><span></span>
                    </p>
                    <p>
                        <span>3.2.1</span><span>、</span><span>&nbsp;</span><span>自行配备上网的所需设备，包括个人电脑、调制解调器或其他必备上网装置。</span><span></span>
                    </p>
                    <p>
                        <span>3.2.2</span><span>、</span><span>&nbsp;</span><span>自行负担个人上网所支付的与此服务有关的电话费用、网络费用等。</span><span></span>
                    </p>
                    <p>
                        <span>3.3</span><span>、</span><span>&nbsp;</span><span>用户点击</span><span>“</span><span>同意以下协议并注册</span><span>”</span><span>按钮，则视为用户同意本协议的所有条款，且具有浏览神州会展平台相关信息、发布需求、发表评价等使用神州会展提供的全部服务的权利能力和行为能力，同意承担由此带来的全部法律责任。</span><span></span>
                    </p>
                    <p>
                        <span>3.4</span><span>、</span><span>&nbsp;</span><span>用户注册、使用神州会展不得出于非法或破坏神州会展秩序的目的，用户保证向神州会展提交的全部信息真实、准确和完整，不存在盗用、借用、买入非本人手机号码进行注册行为，用户若存在上述违规行为，经神州会展发现后，将取缔其会员资格。</span><span></span>
                    </p>
                    <p>
                        <span>3.5</span><span>、</span><span>&nbsp;</span><span>用户注册成功后，应妥善保管其神州会展平台帐户及密码，定期或不定期修改密码，在每次使用神州会展服务完毕后及时退出帐户，以确保帐户安全。用户不得将神州会展平台帐户出借、转让或用作其他非法用途，否则因帐户未妥善保管而造成损失的，用户应承担相应法律责任，除非有证据证明该行为与用户无关。若用户因神州会展平台帐户被盗或因其他非用户原因造成损失的，用户应立即通知神州会展并向公安机关报案。</span><span></span>
                    </p>
                    <p>
                        <span>&nbsp;</span>
                    </p>
                    <h3>四、用户信息保护</h3>
                    <p>
                        <span>4.1</span><span>、</span><span>&nbsp;</span><span>神州会展仅在用户注册、发布需求或使用神州会展手机客户端时，基于用户帐户安全、定位、查询的商品或服务等需要，收集用户的手机号、电子邮箱、地址等必要的个人信息，除此之外，神州会展不会收集任何用户信息。用户同意神州会展基于上述目的及范围收集信息。</span><span></span>
                    </p>
                    <p>
                        <span>4.2</span><span>、</span><span>&nbsp;</span><span>神州会展对收集的用户信息中涉及识别用户个人身份和用户个人隐私的信息进行保护，承诺在未获得用户许可的情况下，不会将用户的上述信息对外公开或提供给任何第三方，但以下情况除外：</span><span></span>
                    </p>
                    <p>
                        <span>4.2.1</span><span>、</span><span>&nbsp;</span><span>用户同意让第三方共享资料。</span><span></span>
                    </p>
                    <p>
                        <span>4.2.2</span><span>、</span><span>&nbsp;</span><span>用户同意公开其个人资料，享受为其提供的产品和服务。</span><span></span>
                    </p>
                    <p>
                        <span>4.2.3</span><span>、</span><span>&nbsp;</span><span>根据法律法规的规定，或行政机关的要求，向行政机关、司法机关或其他法律规定的第三方披露。</span><span></span>
                    </p>
                    <p>
                        <span>&nbsp;</span>
                    </p>
                    <h3>五、神州会展服务</h3>
                    <p>
                        <span>5.1</span><span>、</span><span>&nbsp;</span><span>用户可根据本协议及神州会展公布的相关使用规则，查阅在神州会展平台上发布的会展服务商和会展服务信息，通过神州会展平台查阅具体产品，发布商户评价信息，及百度糯米现有及将来可能提供的其他服务。</span><span></span>
                    </p>
                    <p>
                        <span>5.2</span><span>、</span><span>&nbsp;</span><span>用户在使用神州会展提供的上述服务时，应遵守本协议及神州会展的相关使用规则，遵守自愿、平等、公平及诚实信用原则，不利用神州会展平台侵犯他人合法权益及谋取不正当利益，不扰乱网络服务的正常秩序。</span><span></span>
                    </p>
                    <p>
                        <span>5.3</span><span>、</span><span>&nbsp;</span><span>用户可以在神州会展平台发布参展布展的需求等信息，并可对其进行适当的修改、删除，但不得在百度糯米平台发布包含以下内容的言论：</span><span></span>
                    </p>
                    <p>
                        <span>5.3.1</span><span>、</span><span>&nbsp;</span><span>反对宪法所确定的基本原则，煽动、抗拒、破坏宪法和法律、行政法规实施的。</span><span></span>
                    </p>
                    <p>
                        <span>5.3.2</span><span>、</span><span>&nbsp;</span><span>煽动颠覆国家政权，推翻社会主义制度，煽动、分裂国家，破坏国家统一的。</span><span></span>
                    </p>
                    <p>
                        <span>5.3.3</span><span>、</span><span>&nbsp;</span><span>损害国家荣誉和利益的。</span><span></span>
                    </p>
                    <p>
                        <span>5.3.4</span><span>、</span><span>&nbsp;</span><span>煽动民族仇恨、民族歧视，破坏民族团结的。</span><span></span>
                    </p>
                    <p>
                        <span>5.3.5</span><span>、</span><span>&nbsp;</span><span>任何包含对种族、性别、宗教、地域内容等歧视的。</span><span></span>
                    </p>
                    <p>
                        <span>5.3.6</span><span>、</span><span>&nbsp;</span><span>捏造或者歪曲事实，散布谣言，扰乱社会秩序的。</span><span></span>
                    </p>
                    <p>
                        <span>5.3.7</span><span>、</span><span>&nbsp;</span><span>宣扬封建迷信、邪教、淫秽、色情、赌博、暴力、凶杀、恐怖、教唆犯罪的。</span><span></span>
                    </p>
                    <p>
                        <span>5.3.8</span><span>、</span><span>&nbsp;</span><span>公然侮辱他人或者捏造事实诽谤他人的，或者进行其他恶意攻击的。</span><span></span>
                    </p>
                    <p>
                        <span>5.3.9</span><span>、</span><span>&nbsp;</span><span>损害国家机关信誉的。</span><span></span>
                    </p>
                    <p>
                        <span>5.3.10</span><span>、</span><span>&nbsp;</span><span>其他违反宪法和法律行政法规的。</span><span></span>
                    </p>
                    <p>
                        <span>5.4</span><span>、</span><span>&nbsp;</span><span>用户在使用神州会展提供的服务时，不得有下列行为：</span><span></span>
                    </p>
                    <p>
                        <span>5.4.1</span><span>、</span><span>&nbsp;</span><span>利用神州会展平台从事洗钱、窃取商业秘密、窃取个人信息等违法犯罪活动。</span><span></span>
                    </p>
                    <p>
                        <span>5.4.2</span><span>、</span><span>&nbsp;</span><span>将有关干扰、破坏或限制任何计算机软件、硬件或通讯设备功能的软件病毒或其他计算机代码、档案和程序之资料，加以上载、发布、发送电子邮件或以其他方式传送。</span><span></span>
                    </p>
                    <p>
                        <span>5.4.3</span><span>、</span><span>&nbsp;</span><span>干扰神州会展平台正常运行，非法入侵神州会展服务器、篡改神州会展代码或其他损害神州会展系统的行为。</span><span></span>
                    </p>
                    <p>
                        <span>5.4.4</span><span>、</span><span>&nbsp;</span><span>企图规避神州会展平台的安全设置或网络系统，包括获取用户不应获取的数据，登录未经明确授权的服务器或帐户，或采用运行端口扫描等方式窥探其他网络的安全措施。</span><span></span>
                    </p>
                    <p>
                        <span>5.4.5</span><span>、</span><span>&nbsp;</span><span>以导致神州会展的计算机系统或设施承受不合理负载的方式获取神州会展提供的服务或网站信息，或进行可能导致此类情况出现的行为。</span><span></span>
                    </p>
                    <p>
                        <span>5.4.6</span><span>、</span><span>&nbsp;</span><span>实施任何形式的网络监控，从而截取与自身无关的信息。</span><span></span>
                    </p>
                    <p>
                        <span>5.4.7</span><span>、</span><span>&nbsp;</span><span>利用神州会展平台从事与网上购物无关或不是以购物为目的的活动，试图扰乱正常购物秩序，谋取不正当利益的行为。</span><span></span>
                    </p>
                    <p>
                        <span>5.4.8</span><span>、</span><span>&nbsp;</span><span>注册多个帐户，通过自我邀请、相互邀请或利用多个手机等不正当手段获取任何经济利益。</span><span></span>
                    </p>
                    <p>
                        <span>5.4.9</span><span>、</span><span>&nbsp;</span><span>其他损害他人或神州会展合法权益的行为。</span><span></span>
                    </p>
                    <p>
                        <span>5.5</span><span>、</span><span>&nbsp;</span><span>一经发现用户提供虚假信息或有上述禁止的言论或行为的，神州会展有权采取暂停提供服务、删除违法违规信息、限制用户使用、禁止用户发言、锁定用户帐户等处理措施。若因用户的上述言论或行为给他人或神州会展造成损失的，用户还应承担赔偿责任。</span><span></span>
                    </p>
                    <p>
                        <span>5.6</span><span>、</span><span>&nbsp;</span><span>用户应遵守本协议及神州会展公示的各项服务规则的内容，若因用户违反本协议及服务规则造成损失的，用户应予以赔偿。</span><span></span>
                    </p>
                    <p>
                        <span>&nbsp;</span>
                    </p>
                    <h3>六、服务条款的修改</h3>
                    <p>
                        <span>神州会展有权不定期的制定、修改本协议及</span><span>/</span><span>或相关服务规则，一旦条款及服务内容、规则产生变动，神州会展将会以网站公告的方式进行公示。</span><span></span>
                    </p>
                    <p>
                        <span>&nbsp;</span>
                    </p>
                    <h3>七、服务的中断和终止</h3>
                    <p>
                        <span>7.1</span><span>、</span><span>&nbsp;</span><span>神州会展会尽全力维护平台的正常运行，以向用户提供持续、稳定、安全、顺畅的服务。但用户理解并同意：神州会展对服务页面进行改版、升级网站系统、增加服务功能等须中断服务的操作时，有权暂时中断服务。神州会展将尽可能在实施以上行为时予以提前公告，并尽可能将影响降低到最小。</span><span></span>
                    </p>
                    <p>
                        <span>7.2</span><span>、</span><span>&nbsp;</span><span>用户可自行停止使用神州会展提供的服务，并可向神州会展提交申请，要求封停或注销其帐户。用户帐户被封停或注销后，用户将不能使用神州会展平台除浏览页面外的所有服务，但神州会展仍有权保留用户的所有注册信息及过往记录，对用户在神州会展平台从事违法行为或违反本协议及相关规定的行为，神州会展仍有权行使本协议规定的权利并追究用户的法律责任。</span><span></span>
                    </p>
                    <p>
                        <span>7.3</span><span>、</span><span>&nbsp;</span><span>神州会展可在下列情况下，自行停止向用户提供服务，并封停或注销其帐户，若因用户行为给神州会展造成损失的，用户还应负责赔偿。</span><span></span>
                    </p>
                    <p>
                        <span>7.3.1</span><span>、用户违反本协议相关规定的，不论用户是否直接、间接或者通过他人再次注册成为神州会展用户，神州会展均有权停止向其提供服务。</span><span></span>
                    </p>
                    <p>
                        <span>7.3.2</span><span>、</span><span>&nbsp;</span><span>用户使用虚假信息注册的，包括但不限于使用虚假姓名、虚假地址、虚假手机号、虚假电子邮箱等，神州会展均有权立即停止向其提供服务。</span><span></span>
                    </p>
                    <p>
                        <span>7.3.3</span><span>、</span><span>&nbsp;</span><span>本协议终止或更新时，用户明示不同意接受新协议的。</span><span></span>
                    </p>
                    <p>
                        <span>7.3.4</span><span>、</span><span>&nbsp;</span><span>其他违反神州会展相关规定或致使神州会展或他人遭受利益损害的行为。</span><span></span>
                    </p>
                    <p>
                        <span>&nbsp;</span>
                    </p>
                    <h3>八、责任限制</h3>
                    <p>
                        <span>8.1</span><span>、</span><span>&nbsp;</span><span>不论在任何情况下，神州会展对由于互联网正常的设备维护，互联网络连接故障，电脑、通讯或其他系统的故障，电力故障，罢工，暴乱，骚乱，灾难性天气（如火灾、洪水、风暴等），爆炸，战争，政府行为，司法行政机关的命令或第三方的不作为而造成的不能履行或延迟履行服务不承担责任。</span><span></span>
                    </p>
                    <p>
                        <span>8.2</span><span>、</span><span>&nbsp;</span><span>如因上述不可抗力或其他神州会展无法控制的原因使神州会展平台的信息系统崩溃或无法正常使用导致无法正常提供服务或丢失有关的信息、记录等，神州会展不承担责任。但神州会展会在最大限度内尽可能合理地协助处理善后事宜，并努力使客户免受经济损失及其他损失。</span><span></span>
                    </p>
                    <p>
                        <span>8.3</span><span>、</span><span>&nbsp;</span><span>基于互联网的特殊性，神州会展平台显示的信息可能有一定的滞后性或差错，对此情形用户应知悉并理解；用户须自行辨别真伪，谨慎预防风险。</span><span></span>
                    </p>
                    <p>
                        <span>&nbsp;</span>
                    </p>
                    <h3>九、知识产权</h3>
                    <p>
                        <span>9.1</span><span>、</span><span>&nbsp;</span><span>用户同意，用户在神州会展平台发表的用户评论等信息（以下简称</span><span>“</span><span>信息</span><span>”</span><span>），除署名权、发表权、修改权外的其他知识产权权利（包括但不限于：复制权、发行权、出租权、展览权、表演权、放映权、广播权、信息网络传播权、摄制权、改编权、翻译权、汇编权以及应当由著作权人享有的其他可转让权利），均独家排他无偿许可给神州会展，并同意神州会展以自己名义就所述权利的保护采取任何形式的法律行为，并获得全部赔偿。</span><span>&nbsp;</span><span>本协议已经构成《著作权法》第二十五条所规定的书面协议，其效力及于用户在神州会展平台发布的任何受著作权法保护的作品内容，无论该内容形成于本协议签订前还是本协议签订后。</span><span></span>
                    </p>
                    <p>
                        <span>9.2</span><span>、</span><span>&nbsp;</span><span>神州会展及神州会展许可的关联方有权将用户在神州会展平台发表的用户评论进行使用或者与其他人合作使用，使用范围包括但不限于网站、电子杂志、杂志、刊物等。</span><span></span>
                    </p>
                    <p>
                        <span>&nbsp;</span>
                    </p>
                    <h3>十、通知和公告</h3>
                    <p>
                        <span>10.1</span><span>、</span><span>&nbsp;</span><span>神州会展向用户发送的所有通告，将通过页面公告或电子邮件的方式传送。神州会展的活动信息也将定期通过页面公告及电子邮件方式向用户发送。用户协议条款的修改、服务变更、或其它重要事件的通告都会以此形式进行。</span><span></span>
                    </p>
                    <p>
                        <span>10.2</span><span>、</span><span>&nbsp;</span><span>用户可以选择接受或不接受神州会展通过邮件和短信的形式向其发送订单信息、促销活动等信息。用户选择不接受的，可以随时通知神州会展取消发送。</span><span></span>
                    </p>
                    <p>
                        <span>&nbsp;</span>
                    </p>
                    <h3>十一、法律管辖和适用</h3>
                    <p>
                        <span>11.1</span><span>、</span><span>&nbsp;</span><span>本协议的订立、执行和解释及争议的解决均应适用中华人民共和国大陆地区法律。</span><span></span>
                    </p>
                    <p>
                        <span>11.2</span><span>、</span><span>&nbsp;</span><span>如发生本协议条款与上述法律相抵触时，则这些条款将完全按上述法律规定重新解释，但不影响其它合法条款对用户产生的法律效力和影响。</span><span></span>
                    </p>
                    <p>
                        <span>11.3</span><span>、</span><span>&nbsp;</span><span>本协议的规定是可分割的，如本协议任何规定被裁定为无效或不可执行，则该规定可被删除，不影响其余条款的继续执行。</span><span></span>
                    </p>
                    <p>
                        <span>11.4</span><span>、</span><span>&nbsp;</span><span>如双方就本协议内容或其执行发生任何争议，双方应尽力友好协商解决；协商不成时，任何一方均可向神州会展所在地人民法院提起诉讼。</span>
                    </p>

                </div>
                <Footer></Footer>
            </div>
        );
    }
}

function store2props({authService}) {
    return {
        currentUser: authService.currentUser,
    };
}

export default connect(store2props)(About);